name: Node.js CI
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
        env:
          PORT: ${{ secrets.PORT }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Run tests
        run: npm test
        env:
          PORT: ${{ secrets.PORT }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
