name: Node.js CI
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Create .env file
      run: |
        echo PORT=${{ secrets.PORT }} >> .env
        echo APP_BASE_URL=${{ secrets.APP_BASE_URL }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
    - name: Install dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
    
